version: "2"

services:
  pingfederate:
    image: pingidentity/pingfederate
    environment:
      - SERVER_PROFILE_URL=https://github.com/ashiverick/server-profiles-demo.git
      - SERVER_PROFILE_PATH=pingfederate
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

networks:
    pingnet:
