version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/ashiverick/server-profiles-demo.git
      - SERVER_PROFILE_PATH=pingfederate
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
          # aliases: 
          #   - pingfederate-admin

networks:
    pingnet-internal:
    pingnet-dmz:
